### ISSUE TITLE
Adding a device to a full pool does not allow a user to immediately create new FS

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1234]
I ran a pool out of space, then I added a device, then I tried to create a new FS which failed for `No space left on device`

Transcript:

``` bash
# /root/stratis filesystem create cache_add_pool fs8
Execution failure caused by:
ERROR: Command failed: cmd: "/usr/sbin/mkfs.xfs" "-f" "-q" "/dev/dm-17" "-m" "uuid=871b3038-7239-4533-ac7f-a2fa32a870e8", stdout:  stderr: mkfs.xfs: libxfs_device_zero write failed: No space left on device
# /root/stratis pool list
Name              Total Physical Size  Total Physical Used
cache_add_pool                  4 GiB             4.00 GiB
# /root/stratis pool add-data cache_add_pool /dev/sde
# /root/stratis filesystem create cache_add_pool fs8
Execution failure caused by:
ERROR: Command failed: cmd: "/usr/sbin/mkfs.xfs" "-f" "-q" "/dev/dm-17" "-m" "uuid=07da32a0-6827-435d-be57-c09e59f73975", stdout:  stderr: mkfs.xfs: libxfs_device_zero write failed: No space left on device

# /root/stratis filesystem create cache_add_pool fs8
# /root/stratis pool list
Name              Total Physical Size  Total Physical Used
cache_add_pool                132 GiB             4.53 GiB
```
From an end users perspective, once they add more space to a pool and that operation completes, they should be able to create another FS immediately.

Running current master.  Pool has a couple of devices serving as cache devices too.

**Comment by mulkieran** [comment]
When a device is added to the data tier, it's just a book keeping step these days. Stratis signature is written to the device and it now belongs to the pool. It does not change the size of the thinpool, because we are now allocating lazily.

The problem is really the thinpool's. Why hasn't it taken the opportunity to increase it's size, now that it can? Perhaps because, after having received a lowater event it doesn't get any more events that cause it to run the ```ThinPool::check``` method? That seems the most likely explanation.

**Comment by agrover** [comment]
just call check() after a device is added?

**Comment by mulkieran** [comment]
It is wierd, though, that the second time the creation succeeded. What prompted the ```check()``` function to run in the interim between the first attempt and the second?
