### ISSUE TITLE
Failure to save fs metadata for newly created fs leaves a DM/filesystem mess

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1274]
If a DM device and filesystem are successfully created on filesystem creation, but there is a failure to save the metadata for the new filesystem, no filesystem is recorded in the pool, but the DM device and filesystem are not cleaned up.

See #1254 for details.

**Comment by mulkieran** [comment]
These creation methods are more tricky than deletion methods. Right now, we don't remove the destroyed thing from internal engine data structures unless destruction totally succeeds. Here though, we could partially create, and then fail. We could try to destroy what we had already created and go back to a clean state, but fail in the destruction. What ought we to do then? We need a coherent and consistent plan.

**Comment by mulkieran** [comment]
I think we need to distinguish between "failed" and "shouldn't be recorded in engine data structures". For example, if we manage to create a thin device but fail to put the file system on it then we have failed from the user's point of view. But that doesn't necessarily mean that we shouldn't record the existence of the file system. The ThinDev exists now, and in order to take down the pool, that thindev must be removed. I think that the thing to do is to refine the file systems state or have a separate category or data structure for incomplete file systems.

**Comment by agrover** [comment]
> We need a coherent and consistent plan.

Not going to happen for 1.0.1. :smiley: Maybe for 1.1? I've added #1277 to 1.1 project. 

For 1.0.1, we can try to clean up. True it's not a 100% solution, but based upon further analysis on #1254 (failure is due to destroy() failing; `save_fs()` was never called) the unlikelihood of `save_fs()` failing plus the unlikelihood of cleanup failing if `save_fs()` *does* fail will work in the short term.
