### ISSUE TITLE
BTree* vs Hash* data structures

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#147]
An issue from #144 discussion.

We're currently using a lot of BTreeMaps and the occasional BTreeSet. Should we instead be using HashMap and HashSet?

Rust official guidance on picking a collection: https://doc.rust-lang.org/std/collections/

Other project-specific reasons for using BTree are:
* json serialization, less human-readable if in arbitrary order?
* a general hunch that BTree* is less wasteful of space, with the small numbers of contents we are likely to have
* Not performance-critical, we don't need O(1) lookups

None of these are really all that compelling, IMHO.

The reason to *not* use them (that I can think of at this moment) is if we somehow come to accidentally rely on the ordering, that could cause data-dependent bugs down the road.

Thoughts?

**Comment by mulkieran** [comment]
I'ld rather use the minimal thing, which is Hash* rather than BTree*. We have many temporary internal data structures, as well as more permanent ones. We may actually come to require order, in which case it will be meaningful to switch to BTree*. I have a PR against device-mapper to make Device hashable:
https://github.com/stratis-storage/devicemapper-rs/pull/8.

**Comment by mulkieran** [comment]
Closed by #289.
