### ISSUE TITLE
Log every action that occurs as the result of a command issued to stratisd at the info level

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1648]
Currently, users interact w/ the stratisd D-Bus layer. Every engine action that could occur as a result of a command issued on the D-Bus should be logged. However, this logging should not occurs at the D-Bus layer itself, but in a hypothetical layer between the D-Bus layer and the engine.

**Comment by bgurney-rh** [comment]
We may want to categorize certain "non-volatile" events at a level below "info", to reduce the number of near-useless events in syslog.

A few examples of "non-volatile" events (I'm not sure if that's the correct term to use) would be "stratis pool list", "stratis fs list", etc.  These would be commands that ideally do not make changes to Stratis pools.

**Comment by bgurney-rh** [comment]
Here's the list of "non-volatile" versus "volatile" commands that I compiled earlier:

The "non-volatile" user commands (i.e.: the commands that only read and report status and/or settings, and don't modify any Stratis devices):
```
stratis pool list
stratis filesystem list [pool_name]
stratis blockdev list [pool_name]
stratis daemon redundancy
stratis daemon version
```

The "volatile" commands (the commands that modify a Stratis device):
```
stratis pool create <pool_name> <blockdev> [<blockdev>..]
stratis pool rename <old_pool_name> <new_pool_name>
stratis pool destroy <pool_name>
stratis pool add-data <pool_name> <blockdev> [<blockdev>..]
stratis pool add-cache <pool_name> <blockdev> [<blockdev>..]
stratis filesystem create <pool_name> <fs_name> [<fs_name>..]
stratis filesystem snapshot <pool_name> <fs_name> <snapshot_name>
stratis filesystem destroy <pool_name> <fs_name> [<fs_name>..]
stratis filesystem rename <pool_name> <fs_name> <new_name>
```

**Comment by drckeefe** [comment]
Agreed, for INFO the list of non-volatile commands shouldn't be logged.  We should log each of the volatile commands in INFO, however. 
The event message could follow the same format as the command, so for example
command: # stratis pool create <pool_name> <blockdev> [<blockdev>..]
successful event msg: stratis pool created <pool_name> <blockdev> [<blockdev>..]
failed event msg: stratis pool create failed <pool_name> <blockdev> [<blockdev>..]  < reason for
failure>

Pool destroy is unique because the list of device that were specified to create the pool
does not need to be provided when destroying the pool, however it may be beneficial to provide the list of devices in the event message for success or failure.

**Comment by mulkieran** [comment]
I agree also that only "volatile" commands should be logged.

I would like it to be possible to make a UUID for the message pair, also, for easy searching for the matching end or beginning message as the case might be.

**Comment by mulkieran** [comment]
Let's use "mutating" instead of "volatile". That's what we really mean.

**Comment by mulkieran** [comment]
@jbaublitz will be helping with establishing an infrastructure for the log entries

**Comment by mulkieran** [comment]
Since it is logging, which is really more internal behavior, it doesn't need to be promoted.

**Comment by mulkieran** [comment]
Re-assigning just to me as we discovered significant dependencies during the course of development.
