### ISSUE TITLE
Modify *Action types slightly

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1741]
I think it might be useful to make them more uniform. There's a lot of binariness about them, and I'ld kind of prefer them to be a bit more binary. It's a classic to separate list into empty and other, and I'ld kind of like to do that, even though the component of a Set*Action is actually a Vec, and not a list.

So, change *Action to have two constructors, Identity and Changed.

So, change Set*Action so that it has two constructors, Identity and Changed, and which one is made can be decided on by the ```new``` function based on whether the Vec argument is empty or not.

For RenameAction, have two constructors, Source and NoSource, and let the argument of Source be itself an enumerated type w/ two constructors, Identity and Changed. NoSource is a nullary constructor, as it is now.

I think that this would increase uniformity in a useful way.

**Comment by mulkieran** [comment]
@jbaublitz: Please look into this and see if it is doable. (I was going to let this sit for a while, but I noticed that #1705 has some additions to one action type, and so it seemed best to move this up a bit).

**Comment by jbaublitz** [comment]
@mulkieran I've been attempting to implement both of these changes and I'm seeing potential problems with both. While my original implementation does not have these issues, I'm still open to other suggestions that may be more uniform and not have the problems I'll outline below.

### `Set*Action` as an enum
Making this a two-variant enum becomes an issue because of the inner `Vec`. While this at first glance provides more uniform handling, `Vec`s in an enum can easily be constructed as a zero length vector. This arises from the lack of public/private controls on enums. As a result, we will be forced to check two aspects of the data structure to see if anything changed. One is a newtype variant with an empty `Vec`. The other is the unit variant. Either of these indicates no changes and we cannot force those interacting with the API to choose one over the other, only suggest. This seems to add more complexity any checking that is done on this enum and will bubble up into the D-Bus layer. My current solution only has one possible condition in which an action with no state change was carried out. If we can keep it that way, I think it will make things simpler regardless of what we choose.

### Variants indicating failure to carry out a requested action
I'm beginning to think we should make variants like `NoSource` an error instead. The reason for this is that when we split out the variant into its own enum, we no longer get the benefit of a single type with a type parameter wrapped in a `Result` to indicate the result of the idempotent operation. We have now nested that information in a `Result` and another type that also more or less indicates a failure to carry out the operation. This seems like a duplication of the `Result` type when it could be logically collapsed into one nesting level of return type in `Result`. If `NoSource` did not indicate a failure, I'd be inclined to agree with this, but we essentially would have two layers of error reporting and I'm uncertain that this gives us what we want. I'd almost prefer extending `StratisError` so that all of the error values are contained in one place.

What are your thoughts?

**Comment by mulkieran** [comment]
I'll have to dig into this a little bit more...and it really isn't super urgent.

**Comment by mulkieran** [comment]
Taking off any board. We seem to be getting along ok.

**Comment by mulkieran** [comment]
I think events have overtaken this issue, closing.
