### ISSUE TITLE
Redesign API to rely on ObjectManager

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#175]
We should be able to simplify our DBus API by relying on ObjectManager as the way the client enumerates all objects and their children, and properties of those objects. `GetManagedObjects` will return all object paths, interfaces, and property values for object paths under stratis1.Manager, which will avoid the need for List methods, and give the clients the object paths of all objects that they may use directly, instead of needing another DBus call too look up.

**Current API**
```
// Manager methods
"ListPools";
"CreatePool";
"DestroyPool";
"GetPoolObjectPath";
"GetFilesystemObjectPath";
"GetDevObjectPath";
"GetCacheObjectPath";
"GetErrorCodes";
"GetRaidLevels";
"GetDevTypes";
"ConfigureSimulator";

// Pool Methods
"CreateFilesystems";
"DestroyFilesystems";
"ListFilesystems";
"ListDevs";
"ListCacheDevs";
"AddCacheDevs";
"RemoveCacheDevs";
"AddDevs";
"RemoveDevs";

// Filesystem Methods
"CreateSnapshot";
"Rename";
"SetMountpoint";
"SetQuota";
```

**Proposed API**
```
// Manager methods
ObjectManager interface:
"GetManagedObjects";
stratis1.Manager interface:
"CreatePool";
"ErrorCodes"; // RO property
"RaidLevels"; // RO property
"Version"; // RO property
"ConfigureSimulator";

// Pool interface
"CreateFilesystems";
"AddDevs";
"AddCacheDevs";
"Name"; // RO property
"SetName";
"Uuid"; // RO property
"BlockDevs"; // RO property, array of objectpaths
"CacheBlockDevs"; // RO property, array of objectpaths
"Filesystems"; // RO property, array of objectpaths
"Destroy";

// Filesystem interface
"CreateSnapshot";
"Mountpoint" // RO property
"SetMountpoint"; // (not sure about this & prev, discuss)
"Quota" // RO property ver 2
"SetQuota"; // ver 2
"Destroy";
"Name"; // RO property
"SetName";
"Uuid"; // RO property

// Blockdev interface
"Remove"; // only in version 3.0
"SetUserLocationInfo";
"UserLocationInfo"; // RO property
"DeviceInfo" // RO property with VPD83 serial
"Uuid"; // RO property

// CacheBlockdev interface
"Remove"; // in a future version
"SetUserLocationInfo";
"UserLocationInfo"; // RO property
"DeviceInfo" // RO property with VPD83 serial
"Uuid"; // RO property
```

**Comment by tasleson** [comment]
If you look at udisks they have a bunch of methods which return lists of things.  After running into a number of race conditions which they didn't go into detail about they came up with the object manager interface and thus udisks2 was born.

**Comment by agrover** [comment]
Updated proposal to give pool properties that list associated objects. Object Paths for everything are not meaningful and non-hierarchical; client differentiates based upon supported Interface (e.g. Pool, Filesystem) and build associations based on pool properties referencing other object paths.

**Comment by agrover** [comment]
Note: `BlockDev` and `CacheBlockDev` DBus implementation can happen after the more important three: `Manager`, `Pool`. `Filesystem`.`

**Comment by mulkieran** [comment]
DevTypes is not specified in current implementation. Until we know what it does, probably we should drop it.

**Comment by agrover** [comment]
OK, updated proposal to remove DevTypes.

**Comment by mulkieran** [comment]
OK!

**Comment by mulkieran** [comment]
What's the advantage of moving Pool.DestroyFilesystems to Filesystem.Destroy ?

**Comment by mulkieran** [comment]
Should Manager have a Pools property?

**Comment by agrover** [comment]
> What's the advantage of moving Pool.DestroyFilesystems to Filesystem.Destroy ?

There's a certain level of OOPiness that would be increased by making objects destroy themselves. I think we've been heading in the opposite direction with our pluralized APIs, however. If you prefer, we can undo this change.

**Comment by agrover** [comment]
> Should Manager have a Pools property? It seems unnecessary, because there is only one engine, so the results of GetManagedObjects() are for that engine, but it might be useful.

Useful how?

On a related note, I had a thought about Blockdevs, CacheBlockdevs and Filesystems properties in Pool. We could remove these if instead the child interfaces had a "Pool" property that contained the objectpath of their owning pool. (i.e. point from child to parent instead of parent to child interface). Or heck, we could have both. What are the pros and cons?

**Comment by mulkieran** [comment]
Note: A bug or awkward feature in dbus-rs relating to ```GetManagedObjects```: https://github.com/diwic/dbus-rs/issues/70.

**Comment by mulkieran** [comment]
Regarding OOPiness...I think it is more important that Create* and Destroy* be at the same level.

**Comment by tasleson** [comment]
Having things at the same level is one approach, but I believe that in true OOA/OOP you would have a destroy method on the object as it's a behavior of the object.  Additionally, In this way if the client had a collection of objects of different types, you can leverage polymorphism and simply call destroy on each one.  If you have it at a different layer the client needs to understand the **type** of the object and then apply a unique call.  Thus when new types are added, new code needs to change in more places.

You could also make a single Manager.Delete(object_paths[]) method that can delete object(s) of any type.  Then there would be no question which delete to use and this would allow clients to delete things in heterogeneous or homogeneous collections without round tripping for each object.

**Comment by mulkieran** [comment]
@tasleson:

```DestroyPool``` is not solely a method on the pool object. 

Consider a Vector of Strings. You remove a String from the vector, it's an operation on the Vector. You access that String and remove its trailing 's', that's an operation on the String.

```DestroyPool``` combines aspects of both. It's like a Vector operation, because the engine has to   lose knowledge of the pool just like the Vectors needs to lose knowledge of the string. It's like a String operation, because various things have to be done to clean up the pool that was destroyed. So, it's an operation that spans the engine and the pool.

I would be happy with two operations: one called ```RemovePool``` that worked on the engine and detached the pool from the engine and one called ```DestroyPool``` that worked on the pool and did the work to make it go away. But, failing that, I'ld rather be calling ```DestroyPool``` on the managing object than on the managed object.

Also, for the other pluralized methods, if we can create a bunch of filesystems on a pool; and perhaps realize efficiencies thereby; why should we destroy these filesystems one-by-one and likely realize inefficiencies thereby? I'ld be fine with ```CreatePools``` and ```DestroyPools```, for that matter.

Regarding your last point, you're proposing a significant departure from the current design. Right now, there are no methods that explicitly accept object paths as arguments. I don't know how much sense this would have made before we developed this focus on ```GetManagedObjects()```. But now that this is our plan, it is possible that the Destroy* or Remove* methods, that currently take names, would make just as much sense if they took object paths. This would however, place more of a burden on the client side. For example, the CLI probably takes a name or names, the client side library uses that information and the managed objects information to glean the object paths, and then it calls the appropriate Destroy* or Remove* method. This adds another way of failing on the client side, i.e., failure to find object paths for its criteria, although that problem was also somewhat there in the old approach, so this point doesn't seem really important.

I can see one way in which having an uber-destroy method on the stratis Manager like the one that you describe might save some trouble in the long run. From the point of view of our implementation, it is robust to changes in our conception of the ownership of certain objects. For example, I think that a given filesystem should always belong to one pool. But I'm not so sure that that would always be true of a given device. Another way that it agrees with my viewpoint is that the Manager is the top-level; and all objects eventually belong to it.

However, I think such an approach would also be somewhat challenging to implement in stratisd and would reach down into the engine implementation. The most the stratisd D-Bus layer should do is translate from the object paths to identifiers that the engine understands. Then, it would have to pass that information along to an engine method, which would have to then do some planning in order to decide how and what to do with all these to be deleted object paths. So we have to imagine an ```engine::destroy``` method that takes, perhaps, a list of lists, each list corresponding to a different category of object, pools, devices, filesystems. The further complication is that we're back to wondering whether we really destroy things completely or leave them in a way that they can be recovered. How would this be indicated in your uber-destroy method?

Anyway, I think these are starting to look like largeish issues. @agrover any thoughts?

**Comment by mulkieran** [comment]
Update to proposed API:

```
// Manager methods
ObjectManager interface:
"GetManagedObjects";
stratis1.Manager interface:
"CreatePool";
"DestroyPool",
"ErrorCodes"; // RO property
"RaidLevels"; // RO property
"Version"; // RO property
"ConfigureSimulator";

// Pool interface
"CreateFilesystems";
"DestroyFilesystems",
"AddDevs";
"AddCacheDevs";
"Name"; // RO property
"SetName";
"Uuid"; // RO property
"Filesystems"; // RO property, array of objectpaths

// Filesystem interface
"CreateSnapshot";
"Mountpoint" // RO property
"Quota" // RO property ver 2
"Name"; // RO property
"SetName";
"Uuid"; // RO property
```

Dev and CacheDev interface deferrred until future PR, also setting mountpoint and quota for filesystems.

TODO:

```
// Pool interface
"Filesystems"

// Filesystem interface
"Mountpoint",
"Quota"
"Name",
"Rename" -> "SetName",
"Uuid"
```

**Comment by mulkieran** [comment]
Been working with code in https://github.com/diwic/dbus-rs/pull/74, and would like to propose a change to internal implementation.

The dbus path context can store the UUID of the filesystem or pool, which doesn't change. AFAIU, blockdevs and cachedevs will also have an unchanging UUID. This makes it a convenient, simple, and uniform choice. The only difficulty is that the UUID is usually decided within an engine method, so the engine methods might have to be reworked just a bit, to return the UUID on creation of a filesystem or pool (or perhaps addition of device to pool).

Engine methods ```get_pool()```, ```rename_pool()```, ```destroy_pool()```, and Pool methods ```rename_filesystem()``` ```destroy_filesystems()``` and ```create_filesystems()```, will take a UUID instead of a name as appropriate.

Filesystem and Pool Name properties will be obtained by lookup in the engine using the UUID.

@agrover What do you think?

**Comment by agrover** [comment]
Sounds really good to me.

**Comment by mulkieran** [comment]
Also, Filesystem will have a PoolUuid property, RO.

**Comment by mulkieran** [comment]
@agrover What should the signature of Mountpoint be? If it is a Path, then it can not really be made into a DBus string, and perhaps should be an array of <something>.

**Comment by agrover** [comment]
I think that's fine for now. We have a big TBD around mount points -- it's not yet clear (to me at least) whether mount points are within Stratis's scope, or not.

**Comment by mulkieran** [comment]
Ok.

**Comment by mulkieran** [comment]
@agrover Is AddCacheDevs in Pool interface necessary or desirable at this time?

**Comment by agrover** [comment]
Later, yes. Now, no.

**Comment by mulkieran** [comment]
Then I shall remove it.

**Comment by mulkieran** [comment]
dbus-rs v0.5.2 was committed about a week. It is now possible to do lookup in tree instead of using look-aside tables. Giving it a try.

**Comment by agrover** [comment]
completed, closing
