### ISSUE TITLE
Extend device discovery to identify encrypted devices

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#1782]
We need to extend our existing device discovery framework to identify encrypted devices.

If we think purely of the organization of the data structures returned by ```find_all()``` or an analogous function which is specific to encrypted devices:
* There must be an enumeration for encrypted block devices (not Stratis ones, because that will not be visible). We expect that ```ID_FS_TYPE``` will have value "luks2", I believe.
* Each device presented by the udev enumeration must be examined using libcryptsetup to take a peak at the correct token which must identify the Stratis pool and device UUID. This information is
enough to group the devices by pool UUID. As with the existing code, we ignore the possibility of duplicate Stratis device UUIDs.

An important consideration is that we must handle correctly a situation where some pools are encrypted and some pools are not.

What might conceivably make this trickier is that some devices might be already opened by some outside agencies and thus available as Stratis devices and some, belonging to the same pool, might be still unopened.

**Comment by jbaublitz** [comment]
A couple notes as I get started on this:
1. `TYPE=crypto_LUKS` will be the exact value returned via udev for encrypted devices.
2. I'd like to discuss a little bit more what we plan to store in the LUKS token. For the purpose of this PR, it only matters for the return type of the method I'm stubbing out so it should be relatively easy to work around. My current thought is that we need at the very least keyfile path, pool UUID or name (depending on which makes more sense in the context), and device UUID.

> An important consideration is that we must handle correctly a situation where some pools are encrypted and some pools are not.

I'll investigate this and keep this in mind, but based on what I know of that part of the code base, I think this should actually work relatively nicely with my solution below.

> What might conceivably make this trickier is that some devices might be already opened by some outside agencies and thus available as Stratis devices and some, belonging to the same pool, might be still unopened.

This is thankfully relatively simple to achieve due to the libcryptsetup API. My current thought is that we should iterate through all LUKS devices and confirm that they belong to stratisd and then through all active LUKS devices. For each active device, libcryptsetup allows us to retrieve the path of the physical device on which it exists. We can then compare the set of physical devices that have been activated to the set of physical devices that have not been activated and belong to stratisd. From there we can take two steps: first we open any remaining devices that are inactive. Once we've done this, we construct pools from all of the resulting devicemapper nodes that will be associated with their respective pool UUIDs.

**Comment by mulkieran** [comment]
This seems reasonable, but in the best case we should be able to handle difficult situations where we can not activate the devices. One possible cause would be somebody moving the keyfile. Another cause would be that the contents of the keyfile would be changed. You can throw in additional complexity by having some encrypted devices that correspond to a pool be openable and some not. This is harder to arrange than some other situations, but should definitely be considered a possibility.

To make the solution durable, it may make sense to have multiple stages either for individual devices or for groups of devices.

If it is helpful it might make sense to take adjudication of devices to pools out of the StratEngine implementation where it is now and encapsulate it in a separate module or struct implementation.

Right now ```try_setup_pool``` is the only method that determines where the set of devices ends up, in ```pools``` or in ```incomplete_pools```. But that whole decision making process may become larger and require more than two categories, anyway.

Right now, I'm seeing something like a table of rows and columns where the ```incomplete_pools``` vec is now. The  rows correspond to pool UUIDs, the columns are "unencrypted" and "decrypted". If all items for a particular pool UUID are in the unencrypted column, then it is time to try to setup the pool. If that fails, then maybe all those devices go back in the unencrypted column, or maybe they go into another column indicating that they have failed once to be setup, and are also tagged with some other information, like times tried or cause of failure (which unfortunately is not available yet, but could be made so if necessary).

**Comment by mulkieran** [comment]
Closing and starting a new project issue, since our approach has changed a great deal and requires interaction among multiple parts of the project.
