### ISSUE TITLE
Relax restrictions on encryption passphrase

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#1921]
Our current encryption implementation relies on the user providing a 512-bit randomly generated passphrase in the kernel keyring. After discussing how the KEK is generated from the passphrase supplied by users in cryptsetup, it seems that we should be able to relax this restriction on the passphrase with no adverse effects.

Things to consider:
* Password checking library to check for passphrase strength.
* Allowing variable-length passphrases and clearly document the maximum length.
* We should still support randomly generated passphrases even with non-printable characters if the user would prefer to use a byte-based key as opposed to a traditional passphrase with printable characters only.

**Comment by jbaublitz** [comment]
Yes, that is what I understood as well.

**Comment by mulkieran** [comment]
In standup we agreed:

* No internal quality checking of key in keyring
* Allow variable length, with a defined maximum length for the key
* Accept PBKDF defaults on initialization of encrypted device
* Document the user's responsibility to choose a reasonably secure key to insert into the kernel keyring in the first place

The consequence of these choices are that, due to PBKDF defaults, each device will require about two seconds for activation, for example when stratisd is starting up.
