### ISSUE TITLE
In StratPool::add_blockdevs(), we should handle the case for adding zero devices to the data tier

### ISSUE THREAD

**Issue by lleshchi** [stratis-storage/stratisd#1973]
When zero devices are added to the Cache Tier, the case is handled separately. https://github.com/stratis-storage/stratisd/blob/develop-2.0.1/src/engine/strat_engine/pool.rs#L359

A similar handling of this case for the Data Tier might be reasonable, rather than calling `backstore.add_datadevs` on an empty list. 
https://github.com/stratis-storage/stratisd/blob/develop-2.0.1/src/engine/strat_engine/pool.rs#L396

**Comment by mulkieran** [comment]
I'll take a look at this...this might interact with #1968.

**Comment by mulkieran** [comment]
@lleshchi, @jbaublitz It looks like it is reasonable to combine this w/ https://github.com/stratis-storage/stratisd/pull/1969. But I still have to think out the implications a bit.

**Comment by mulkieran** [comment]
@lleshchi, @jbaublitz  See the comment I added here:
https://github.com/stratis-storage/stratisd/blob/develop-2.0.1/src/engine/strat_engine/pool.rs#L364.

The phrasing is poor, it may have gone out of date. But I know why I added it. I did not want to have stratisd suspend the pool if the list of devices to add was empty, because suspending the pool is a heavyweight operation and it should not be done for no reason. But if you look at the action for the data devs, why run check on the pool if no data devs should be added. check is not as heavy weight as suspend, but it still is a lot of business for nothing. So that call to check should be omitted if no devices are actually added in the data case as well. The justification is the same for the cache as for the data. So that's a change that it is worthwhile to make. But note that that is not your original question.

**Comment by mulkieran** [comment]
Basically, what we want to do is hoist ```devices::process_and_verify_devices``` up so that it can be used in the StratPool implementation. If it returns an empty list there is nothing to be done. Clearly, ti will return an empty list if the list of paths it is passed is an empty list, but it will also do that in other circumstances. For the SimEngine, there is no extra check it can do, so it will return an empty list only if the list it is passed is empty. For init_cache, where we have that idempotency operation, we would use ```process_and_verify_devices``` as well.

But that hoist operation is tricky, so we haven't done it yet; the extraction of that method from a larger method was only completed a couple of months ago.

So, should the empty list of paths also be checked for in the case of the data devices as well as the cache devices at this time, given that we're probably not going to hoist ```process_and_verify_devices``` up immediately? I think that would be fine, because it would increase symmetry between the cache and data device handling. But eventually we would throw that specific check out, replacing it with the call to ```process_and_verify_devices```, I hope.

**Comment by mulkieran** [comment]
So, you're welcome to tackle all those things while working on #1969. It might make it easier to handle, actually. Good luck!
