### ISSUE TITLE
regain space after remove file

### ISSUE THREAD

**Issue by rm-canella** [stratis-storage/stratisd#2012]
The malfunction that I am going to describe was reproduced on a computer with the following characteristics:
Stratis versione 2.0.1
Fedora release 32 (Thirty Two)
Kernel: Linux 5.6.8-300.fc32.x86_64

I create a stratis file system and inside I create two 10 GB files:
> ls -l
> total 20972800
> -rw-------. 1 root root 10737418240 May  7 09:44 file_01
> -rw-------. 1 root root 10737418240 May  7 09:44 file_02

> stratis fs
> Pool Name         Name   Used        Created             Device                          UUID                            
> stratis_pool_01   test   20.54 GiB   May 07 2020 09:34   /stratis/stratis_pool_01/test   c2c93f99bf394cc486036851a2f9f485

> stratis pool
> Name                                   Total Physical
> stratis_pool_01   931.51 GiB / 20.59 GiB / 910.92 GiB

I delete a 10GB file and check the file system size and as you can see the file system size is not increased by 10GB:

> ls -l
> total 10486400
> -rw-------. 1 root root 10737418240 May  7 09:44 file_01
> 
> stratis fs
> Pool Name         Name   Used        Created             Device                          UUID                            
> stratis_pool_01   test   20.54 GiB   May 07 2020 09:34   /stratis/stratis_pool_01/test   c2c93f99bf394cc486036851a2f9f485
> 
> stratis pool
> Name                                   Total Physical
> stratis_pool_01   931.51 GiB / 20.59 GiB / 910.92 GiB

I have found to stop the service stratisd and to restart the computer, but the problem remains; only by destroying the filesystem does the pool size return correct.

**Comment by drckeefe** [comment]
@rm-canella Good question.  The file was deleted and the filesystem now reports the correct space used, but the pool is still managing 20GiB.  This happens because the filesystem hasn't told the pool
that the data previously written has been deleted.  There are two typical methods to handle this.  

1. Use the utility fstrim to free up unused blocks which were deleted by the filesystem.  This can be run periodically by hand when you want to free space, or it can be used in a crontab to run on a  schedule (say once a day or once a month). 
2. When mounting the filesystem you can mount with the discard flag.  When the discard flag is used the filesystem will let the pool know when to free unused blocks.

**Comment by rm-canella** [comment]
@drckeefe trying your suggestions the size is updated correctly.
Thank you so much for your intervention
