### ISSUE TITLE
Export sets of devices not yet assembled into pools as first-class objects on the D-Bus

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#2194]

**Comment by mulkieran** [comment]
Things to export on the D-Bus:

* interface: org.storage.stratis2.device_set: not yet pools but grouped by a pool UUID
  * property: Uuid: stored in the usual fashion, UUID of the pool to which all the devices belong
  * additional properties might include some special characteristic of the set, but PoolUuid should be enough for now

The children ought to be individual devices. Each _device_, not blockdev, can store its parent as blockdevs do their pools.
  * property: Device_Set: object path
  * property: Uuid: this is the Stratis UUID for the device: stored as a string
  * property: Encrypted: whether or not the device is an encrypted device with encryption managed by Stratis (the device may be open or closed): bool
  * property: PhysicalPath: same definition as for blockdevs, note that there is no really useful analogue to blockdev's DevNode in the case where the device is unopened: string

  * FetchProperties interface keys:
       * Locked: always false if device is unencrypted, true if the device is encrypted and locked (maybe this should be a true D-Bus property too)

**Comment by mulkieran** [comment]
@mvollmer, @drckeefe, @jbaublitz: Please comment on the design. I think it's fine to focus on just what properties are exported and defer talking about methods until later.

**Comment by mvollmer** [comment]
Looks good to me.

**Comment by jbaublitz** [comment]
> Properties to export on the D-Bus:
> 
> * interface: org.storage.stratis2.device_set: not yet pools but grouped by a pool UUID
>   
>   * property: Uuid: UUID of the pool to which all the devices belong: string
>   * additional properties might include some special characteristic of the set, but PoolUuid should be enough for now
> 
> The children ought to be individual devices. Each _device_, not blockdev, can store its parent as blockdevs do their pools.
> 
> * interface: org.storage.stratis2.device
>   
>   * Device_Set: object path
>   * Uuid: this is the Stratis UUID for the device: string
>   * Encrypted: whether or not the device is an encrypted device with encryption managed by Stratis (the device may be open or closed): bool
>   * PhysicalPath: same definition as for blockdevs, note that there is no really useful analogue to blockdev's DevNode in the case where the device is unopened: string
>   * FetchProperties interface keys:
>     
>     * Locked: always false if device is unencrypted, true if the device is encrypted and locked (maybe this should be a true D-Bus property too): bool

I think that there are a couple considerations here. `Locked` isn't really a piece of identifying information which is the line we've drawn for `FetchProperties`. I'd argue that it's not identifying mostly because if `LockedPools` is not considered identifying as it's in `FetchProperties` as well, this probably isn't either. However, I think this also brings back up the discussion of whether we want to eventually change how we're handling `FetchProperties` and encode errors in real D-Bus properties instead of using `FetchProperties`. The reason this makes me think of that is that it may be helpful to have an property-changed signal sent for the `Locked` property if someone unlocks a device, and we've discussed how that might be done with `FetchProperties`, but I don't think we'll be able to be quite as granular about which property in `FetchProperties` has changed with our current design. Obviously, we'll have to discuss the implications of this more, but those are my thoughts looking at this.

>     * DeviceNumberMajor:  device major number: type is numeric, TBD
>     * DeviceNumberMinor:  device minor number: type is numeric, TBD
> 
> I think these properties are all pretty good ones. There are a very large number of possible methods that could be exposed. Possible ones for the devices sets are: unlock() in the case that the pool is encrypted, reload() - means drop all data for this device set and then rescan, destroy() - wipe all the devices of identifying Stratis information and forget about the set, remove() - identify a particular device to remove from the device set, setup() - attempt to set up as a pool.

Other than these considerations, I have no concerns. Looks good!

**Comment by mulkieran** [comment]
We need to consider this to be blocked by multi-threading work.

**Comment by mulkieran** [comment]
I think we should consider this issue obsolete. We have settled on a property object, and that is working pretty well for us.
