### ISSUE TITLE
When trying to create a new pool from a block device, it gives me an error saying udev information indicates that device /dev/sdb is a block device which appears to be owned.

### ISSUE THREAD

**Issue by ginhiki** [stratis-storage/stratisd#2599]
when i enter the command 

`stratis pool create mypool /dev/sdb`

It gives me an error stating

`Execution failed:
stratisd failed to perform the operation that you requested. It returned the following information via the D-Bus: ERROR: Engine error: At least one of the devices specified was unsuitable for initialization: Engine error: udev information indicates that device /dev/sdb is a block device which appears to be owned. 
`

What could be the issue here? Sorry i am kinda new to linux. Using Fedora 34, with Kernel 5.11.20-300.fc34.x86_64

**Comment by mulkieran** [comment]
Stratis tries to avoid ever claiming for its own, and writing to, devices that appear to be in use by some other, non-Stratis, entity. It uses the contents of the udev database to determine whether or not the device is already in use. Can you post the result of typing ```udevadm info /dev/sdb```? Also, can you verify that the error message indicates ```/dev/sdb1```, not ```/dev/sdb``` which is the argument to the ```create``` command? Typically, we would expect to see ```/dev/sdb``` in the error result, since that is what you entered.

**Comment by ginhiki** [comment]
> Stratis tries to avoid ever claiming for its own, and writing to, devices that appear to be in use by some other, non-Stratis, entity. It uses the contents of the udev database to determine whether or not the device is already in use. Can you post the result of typing `udevadm info /dev/sdb`? Also, can you verify that the error message indicates `/dev/sdb1`, not `/dev/sdb` which is the argument to the `create` command? Typically, we would expect to see `/dev/sdb` in the error result, since that is what you entered.

yeah that sdb1 was my bad, but got the same error by using sdb too, updated my post. But i found the solution, even though i wiped out the block devices using fdisk, it still contained fs signature  cause of which i couldn't create the pool. I wiped out the fs signature via 

`wipefs -a /dev/sdb` 

and then was able to create the pool.
