### ISSUE TITLE
Why do we store device size in the MDA on a block device?

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#270]
I'm puzzled by this, because we read the device size in order to find it to store it using ```blkdev_size()``` method. What advantage do we gain by storing it in metadata?

**Comment by agrover** [comment]
This is because block devices can be extended underneath us. There's still a lot to nail down in this area -- does Stratis just start using the extra space or wait for some indication it can expand? Having the redundant info means we can recognize when this happens. Also, scenarios where a Stratis block device's contents are dd'd to another smaller device that is then substituted, this is detectable. Using a truncated blockdev would likely cause corruption, and Stratis could detect this and refuse.

**Comment by mulkieran** [comment]
Ok!
