### ISSUE TITLE
Handle attaching a pool with the same name as an existing pool

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#272]
@mulkieran

Based on previous discussion around renaming issues, what about a case where pool `foo` is created on machine A, and then physically reattached to machine B that also already has a pool `foo`?

ZFS handles this with an explicit export/import step, see http://thegeekdiary.com/solaris-zfs-how-to-import-2-pools-that-have-the-same-names/

We could consider that approach. Another approach might be to allow pools with the same names, but require they be referenced by UUID instead of name if non-unique.

**Comment by mulkieran** [comment]
I don't like second approach much, because it requires detecing when uniqueness property no longer holds and behaving differently in that case. Detection and modifying behavior would probably both be a pain.

ZFS approach makes more sense, but Stratis does not explcitly import pools, it just grabs what it sees when it starts up. So, it would have to do a check, and fail if, during global Stratis setup, there was a name collision.

So, then comes the quesion of what is Stratis to do if it is already is set up, and previously created pool is to be added. That is like the import situation of ZFS. We currently have no functionality existing for that situation. Question are:

1. Add automatically or require explicit instruction?
2. How to handle name collision. IMHO, auto-renaming by munging is always a source of woe, we should try to avoid it. So, if we want to maintain uniqueness property, either choice of (1) requires that an error occur. In the case of automatic addition, this error would be less likely to be noticed, but a good test case. In the case of explicit addition, this error would be much more likely to be noticed.

**Comment by agrover** [comment]
For 1.0, let's just reject pools with the same name as an existing pool.

**Comment by agrover** [comment]
I've confirmed that we explicitly check if a pool with the same name already exists in `setup_pool()` so we're good for 1.0. This bug is still relevant because we would like to cope with this better someday.

**Comment by mulkieran** [comment]
I believe this is obsolete. A pool with the same name as an already set up pool can be set up if the conflicting pool is renamed.
