### ISSUE TITLE
What to do when stratisd is running but no pools is somewhat context-dependent

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#345]
If started by systemd, maybe it should just exit. If started by user attaching to D-Bus and calling method, should stick around. This can be managed in a number of ways.

**Comment by tasleson** [comment]
Related: https://github.com/stratis-storage/stratisd/issues/769

**Comment by tasleson** [comment]
This has been addressed by setting up the default configuration so that `stratisd` starts at boot when installed.  If a user runs the CLI they will get an error if the daemon isn't running.  The assumption is if they install the package the daemon should always be configured to run by default.

Associated issues:
https://github.com/stratis-storage/stratisd/issues/712
https://github.com/stratis-storage/stratisd/issues/1102
https://github.com/stratis-storage/stratisd/issues/1199
