### ISSUE TITLE
error adding luks_device as cache to pool

### ISSUE THREAD

**Issue by sosyco** [stratis-storage/stratisd#3501]
Hi,
I have to luks devices generated with "cryptsetup --cipher aes-xts-plain64 --key-size 512 --hash sha512 --iter-time 5000 --use-random --verify-passphrase luksFormat /dev/xxx" 
and opened with "cryptsetup open --type luks /dev/xxx big" (HDD), "cryptsetup open --type luks /dev/yyy fast" (SSD).

Generating a pool0 on big works fine, but adding a cache ends always with:
 
The sector sizes of the devices proposed for extending the data tier, BLKSSSZGET: 512 bytes, BLKPBSZGET: 512 bytes, do not match the effective sector sizes of the existing data devices, BLKSSSZGET: 4096 bytes, BLKPBSZGET: 4096 bytes

Is this a problem of generating the devices or working stratis-cli?

**Comment by jbaublitz** [comment]
Hi @sosyco, I think this is a problem with formatting. I'll defer to @mulkieran for details because she is the one who implemented this check, but I think that what's happening is that the sector size changes when you initialize a cache from 512 to 4k. If you format all of the disks with `luksFormat --sector-size 4096`, I *think* this should resolve the problem. @mulkieran Can you confirm that?

**Comment by sosyco** [comment]
> Hi @sosyco, I think this is a problem with formatting. I'll defer to @mulkieran for details because she is the one who implemented this check, but I think that what's happening is that the sector size changes when you initialize a cache from 512 to 4k. If you format all of the disks with `luksFormat --sector-size 4096`, I _think_ this should resolve the problem. @mulkieran Can you confirm that?

Yes, 
this solves the problem.

**Comment by jbaublitz** [comment]
Okay great! Closing.
