### ISSUE TITLE
Should filter_devs return something different?

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#409]
In looking at filter_devs, it doesn't seem to actually filter... if anything is wrong with any of the blockdevs it returns an Err, unless I'm reading it wrong.

I'm wondering if instead of returning an `EngineResult<Vec<>>` it really wants to return a `Vec<EngineResult<>>`? This would allow it to disqualify blockdevs from being used but still allow things to proceed with the remaining ones. @mulkieran what do you think?

**Comment by mulkieran** [comment]
You're reading it correctly. Probably ```filter_devs``` was a bad name to choose. The choice of the return type was deliberate, though, because returning an error on any problem with the interaction is really the simplest choice. We could change that, but we should have a well-worked out reason and plan for the change.
