### ISSUE TITLE
Remove 'force' from D-Bus API

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#613]
Given a list of devnodes that are passed as arguments when creating or extending a pool, each devnode could:

1. Appear unowned. This device can then be initialized.
2. Appear to be owned by something not Stratis. We say that if force is set, the devnode is initialized, but if not, we error out. This might not be correct. What if the devnode is part of the Stratis stack, but not a blockdev? With force flag set, could we end up initializing it and destroying our pool?
3. Appear to be owned by Stratis.
  1. Appear to be owned by the specified pool. In that case it may be:
      1. Already known in the pool. We should verify that the devnode's information fits our existing blockdev in our data structure. If it doesn't we should panic.
      2. Unknown to the pool. If that is the case, an error is the only appropriate course.
  2. Appear to be owned by some other Stratis pool. In that case, the pool may be:
      1. Owned by the current Stratis engine. If that is the case, an error is the only appropriate course.
      2. Unowned by the current Stratis engine. If that is the case, an error is the only appropriate course.

Note, however, that these conditions only pertain of what to when initializing or adding devices to a single pool. There is also the question of what to do at the higher level in two different situations, where a pool is being created for the first time, or where it is being added to. 

Some further discussion here: https://github.com/stratis-storage/stratisd/pull/563/files

I personally think we should get rid of the ```force``` flag entirely.

**Comment by agrover** [comment]
"force flag in cli, not in the api"

**Comment by agrover** [comment]
I think what this means is that functionality of (2) above -- checking for previously-used blockdevs and conditionalizing their acceptance based on the `force` flag in the API -- should instead be moved into the CLI. API methods with `force` should lose it, and instead have the behavior as if `force` was true. The API call should still check (and fail with an error) for (3, 4, 5).

**Comment by mulkieran** [comment]
as if ```force``` false?

**Comment by agrover** [comment]
A. behavior as if `force` is false: Stratisd will refuse to use blockdevs whose first 8KiB (?) is not zeroed. stratis-cli should zero first 8K of blockdevs if --force is given on the cmdline so Stratisd will accept them.

B. behavior as if `force` is true: Stratisd will use blockdevs which have nonzero data, as long as they aren't part of an existing Stratis pool. stratis-cli should check (using libblkid?) and return an error if something is found, rather than calling the API, unless --force is given on the cmdline, in which case it just calls the API.

I was thinking B, but are you saying you think A would be better? I think B makes it easier to implement better error messages in stratis-cli if a sig is found. And there's less room for ambiguity about what blockdevs are acceptable to the API.

**Comment by mulkieran** [comment]
What about problem (2) in the original post?

**Comment by agrover** [comment]
I was talking about (2). At the API level we'd check it didn't somehow belong to ourselves, but would proceed even if there was nonzero bytes on it. The CLI could check this instead of the API, and error out if it wanted, but the API would not. Like I said above, this would remove the `force` flag, and would keep the API's behavior as if `force` was true.

**Comment by tasleson** [comment]
I think by removing the checks in the engine and assuming `force` we open ourselves up with a race condition.  A client cannot check a device (precondition) and get a Stratis signature written on it atomically.  Furthermore, it's possible that two or more API users could step on each other when each of them creates a pool at the same time.  Each API call will succeed (if API call assumes force), but only the second API call invocation on creating a pool will still be intact at the end.

Thinking about this some more, I'm leaning towards removing the force in the API, but not allowing the daemon to destroy an existing signature.  Thus this would force the API caller or CLI user to ensure that any block device has no signature on it.  This would prevent concurrent API users from stepping on one another, it wouldn't prevent different users or applications from stepping on each other though and it doesn't totally remove the race window, but it does limit it as small as it can be.

Thoughts?

**Comment by agrover** [comment]
Since API calls are serialized, using /dev/sde in pool foo2 would fail if it were just recently used to create pool foo1. It would be a case of 5.i, as listed in the initial issue text above.

That said, I think you're basically agreeing [with @mulkieran](https://github.com/stratis-storage/stratisd/issues/613#issuecomment-357090671)  that after "force" arg is removed, behavior should be as if "force" was false, rather than true. Assuming we proceed with this approach, the problem switches from "oops, I used a blockdev that I didn't mean to use" to "why won't Stratis accept this blockdev I'm giving it?" Admittedly a less frightening problem for the user to have. Probably the right approach.

But in implementing this, I think we need to document exactly what Stratis's requirements are to use a blockdev, since it'll now be the cli (or other API user) that needs to ensure blockdevs are acceptable. (We still do want the cli to have a --force option.) Will the API only accept entirely zeroed blockdevs, or first-N-bytes zeroed, or can there be nonzero bytes if no blkid-recognized signatures are present? I'm fine with pretty much whatever, as long as we document it.

**Comment by tasleson** [comment]
> Since API calls are serialized, using /dev/sde in pool foo2 would fail if it were just recently used to create pool foo1. It would be a case of 5.i, as listed in the initial issue text above.

This would only be true if we didn't have  the behavior of `force` being the default

> no blkid-recognized signatures are present

This is what I was thinking, basically what the result of `wipefs -a <device>` would be.

**Comment by mulkieran** [comment]
Only devices that have been decided to be ```DevOwnership::Theirs``` may be forcibly overwritten. This category includes multipath member devices, which are not handled in any special way in ```blockdevmgr::initialize```. Based on that, I think that it would be reasonable to say that not allowing force would have have the effect of eliminating an existing bug in our code (because I think it would be always wrong for stratisd to claim a multipath member device).
