### ISSUE TITLE
Unhelpful error message when missing executable

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#766]
If you're missing the `xfsprogs` package when you try to create a pool you will get the message:

`Execution failed: 4: entity not found`

This could be clearer.

**Comment by mulkieran** [comment]
Related: #530.

**Comment by tasleson** [comment]
Related: https://github.com/stratis-storage/stratisd/issues/771

**Comment by mulkieran** [comment]
I'm going to consider this closed by #986. At this point stratis-cli will never report:

```
Execution failed: 4: entity not found
```

because 

1. the engine will have promptly exited, on discovering that the binaries it relies on does not exist. So, stratis-cli, when invoked to do anything, will report instead a D-Bus exception and will summarize its best guess as that the Stratis daemon is not running OR

2. the engine will have found the necessary executables, which will now have gone missing. In that case, the daemon will put an error on the D-Bus, and the error will be the current string, which is: "Executable previously located at ```<absolute path of executable>``` seems to have been removed since stratisd was started".
