### ISSUE TITLE
Probably BlockDev's path should be a Path, not a PathBuf

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#92]
It doesn't seem to need the extra functionality of PathBuf.

**Comment by agrover** [comment]
Even if we don't modify it, the thing we need with PathBuf is that it is owned, unlike [Path](https://doc.rust-lang.org/std/path/struct.Path.html). If we used a reference like &Path, then the lifetime of the BlockDev would be limited to the scope it was created, see https://doc.rust-lang.org/book/lifetimes.html#in-structs, which doesn't fly because we want to insert (move) the BlockDev into a Vec that will outlive the calling scope, and the compiler won't allow it.

**Comment by mulkieran** [comment]
I found that out, more or less, when I tried to make the change :) But it seems like it should never be necessary to use a completely different class just to solve a lifetime problem.

**Comment by agrover** [comment]
agree, these pairs of types (&str and String, Path and PathBuf, OsStr and OsString, CStr and CString) are a pain, and why the heck does Rust need EIGHT string types. (Not that there aren't reasons, but yuck.)
